apiVersion: v1
kind: Pod
metadata:
  name: k8scar-pod
spec:
  nodeName: k8scar
  containers:
  - name: k8scar
    image: ubuntu:k8scar-0.92
    securityContext:
      privileged: true
    command: [ "/bin/bash" , "-c" ]
    args: [ "while true ; do sleep 300 ; done ;" ] 
    volumeMounts:
    - mountPath: /dev/car/sr04
      name: us-volume
    - mountPath: /dev/car/motor
      name: motor-volume
    - mountPath: /home/pi/remote-car
      name: cloudos-volume
  volumes:
  - name: us-volume
    hostPath:
            #sr04 path
      path: /dev/car/sr04
      type: CharDevice
  - name: motor-volume
    hostPath:
      path: /dev/car/motor
      type:  CharDevice
  - name: cloudos-volume
    hostPath:
      path: /home/pi/remote-car
      type:  DirectoryOrCreate
